# Generated by Django 2.0.4 on 2018-04-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180415_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, choices=[('ABS', 'Abstract'), ('AER', 'Aerial'), ('ANI', 'Animals'), ('ARC', 'Architecture'), ('BNW', 'Black and White'), ('FAM', 'Family'), ('FAS', 'Fashion'), ('FIA', 'Fine Art'), ('FOO', 'Food'), ('JOU', 'Journalism'), ('LAN', 'Landscape'), ('MAC', 'Macro'), ('NAT', 'Nature'), ('NIG', 'Night'), ('PEO', 'People'), ('PEA', 'Performing Arts'), ('SPO', 'Sport'), ('STL', 'Still Life'), ('STR', 'Street'), ('TRA', 'Travel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, choices=[('ABS', 'Abstract'), ('AER', 'Aerial'), ('ANI', 'Animals'), ('ARC', 'Architecture'), ('BNW', 'Black and White'), ('FAM', 'Family'), ('FAS', 'Fashion'), ('FIA', 'Fine Art'), ('FOO', 'Food'), ('JOU', 'Journalism'), ('LAN', 'Landscape'), ('MAC', 'Macro'), ('NAT', 'Nature'), ('NIG', 'Night'), ('PEO', 'People'), ('PEA', 'Performing Arts'), ('SPO', 'Sport'), ('STL', 'Still Life'), ('STR', 'Street'), ('TRA', 'Travel')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
