# Generated by Django 2.0.4 on 2018-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180416_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Aerial', 'Aerial'), ('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Black and White', 'Black and White'), ('Family', 'Family'), ('Fashion', 'Fashion'), ('Fine Art', 'Fine Art'), ('Food', 'Food'), ('Journalism', 'Journalism'), ('Landscape', 'Landscape'), ('Macro', 'Macro'), ('Nature', 'Nature'), ('Night', 'Night'), ('People', 'People'), ('Performing Arts', 'Performing Arts'), ('Sport', 'Sport'), ('Still Life', 'Still Life'), ('Street', 'Street'), ('Travel', 'Travel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Aerial', 'Aerial'), ('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Black and White', 'Black and White'), ('Family', 'Family'), ('Fashion', 'Fashion'), ('Fine Art', 'Fine Art'), ('Food', 'Food'), ('Journalism', 'Journalism'), ('Landscape', 'Landscape'), ('Macro', 'Macro'), ('Nature', 'Nature'), ('Night', 'Night'), ('People', 'People'), ('Performing Arts', 'Performing Arts'), ('Sport', 'Sport'), ('Still Life', 'Still Life'), ('Street', 'Street'), ('Travel', 'Travel')], max_length=20, null=True),
        ),
    ]
