# Generated by Django 2.0.4 on 2018-04-16 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180416_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatarImage',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
