# Generated by Django 2.0.4 on 2018-04-16 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180416_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatarImage',
            field=models.ImageField(blank=True, default='http://via.placeholder.com/200x200', null=True, upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
