# Generated by Django 2.0.3 on 2018-04-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_image_sum_of_likes_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='LikedMember',
            field=models.ManyToManyField(null=True, related_name='member_liked', to='index.Member'),
        ),
    ]
