# Generated by Django 2.0.4 on 2018-04-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='avatarImage',
        ),
    ]
