# Generated by Django 2.0.4 on 2018-04-24 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_remove_member_avatarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatarImage',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
